SELECT BOOK.AUTHOR_ID AS AUTHOR_ID, 
    AUTHOR.AUTHOR_NAME AS AUTHOR_NAME,
    BOOK.CATEGORY AS CATEGORY,
    SUM(BOOK.PRICE*BOOK_SALES.SALES) AS TOTAL_SALES
FROM BOOK JOIN BOOK_SALES ON BOOK.BOOK_ID = BOOK_SALES.BOOK_ID
    JOIN AUTHOR ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
WHERE YEAR(BOOK_SALES.SALES_DATE)=2022 AND MONTH(BOOK_SALES.SALES_DATE)=1
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC 

# SELECT *
# FROM BOOK_SALES

# SELECT *
# FROM BOOK