SELECT DISTINCT(A.CART_ID)
FROM CART_PRODUCTS AS A JOIN CART_PRODUCTS AS B ON A.CART_ID=B.CART_ID
WHERE A.NAME LIKE 'MILK' AND B.NAME LIKE 'YOGURT' OR
        B.NAME LIKE 'MILK' AND A.NAME LIKE 'YOGURT'
ORDER BY CART_ID