SELECT ORDER_ID, PRODUCT_ID, DATE_FORMAT(OUT_DATE,'%Y-%m-%d') AS 'OUT_DATE',
(CASE 
    WHEN (YEAR(OUT_DATE)<=2022 AND MONTH(OUT_DATE)<=4) OR (YEAR(OUT_DATE)=2022 AND MONTH(OUT_DATE)=5 AND DAY(OUT_DATE)=1) THEN '출고완료'
    WHEN YEAR(OUT_DATE)>=2022 AND MONTH(OUT_DATE)>=5 AND DAY(OUT_DATE)>=1 THEN '출고대기'
    WHEN OUT_DATE IS NULL THEN '출고미정'
END) AS '출고여부'
FROM FOOD_ORDER
ORDER BY ORDER_ID ASC