SELECT II.ITEM_ID, II.ITEM_NAME, II.RARITY 
FROM ITEM_TREE AS A LEFT JOIN ITEM_TREE AS B ON A.ITEM_ID = B.PARENT_ITEM_ID
JOIN ITEM_INFO AS II ON A.ITEM_ID = II.ITEM_ID
WHERE B.ITEM_ID IS NULL
ORDER BY II.ITEM_ID DESC