SELECT A.ID, CASE
                WHEN COUNT(B.ID) = 0 THEN 0
                ELSE COUNT(B.ID)
            END AS CHILD_COUNT
FROM ECOLI_DATA AS A LEFT JOIN ECOLI_DATA AS B ON A.ID=B.PARENT_ID
GROUP BY A.ID
ORDER BY ID ASC