SELECT P.PRODUCT_CODE AS 'PRODUCT_CODE', P.PRICE * SUM(OS.SALES_AMOUNT) AS 'SALES'
FROM OFFLINE_SALE AS OS JOIN PRODUCT AS P
    ON OS.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.PRODUCT_ID
ORDER BY SALES DESC, PRODUCT_CODE ASC
