SELECT AO.ANIMAL_ID AS 'ANIMAL_ID', AO.NAME AS 'NAME'
FROM ANIMAL_INS AS AI RIGHT JOIN ANIMAL_OUTS AS AO ON AI.ANIMAL_ID=AO.ANIMAL_ID
-- WHERE AO.DATETIME-AI.DATETIME
ORDER BY (AO.DATETIME-AI.DATETIME) DESC
LIMIT 2