SELECT DISTINCT(CRCRH.CAR_ID) AS CAR_ID, CRCC.CAR_TYPE AS CAR_TYPE, ROUND(CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) / 100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH
JOIN CAR_RENTAL_COMPANY_CAR AS CRCC ON CRCC.CAR_ID = CRCRH.CAR_ID
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP ON CRCC.CAR_TYPE = CRCDP.CAR_TYPE
WHERE CRCC.CAR_TYPE IN ('세단','SUV')
AND CRCC.CAR_ID NOT IN (SELECT CAR_ID
                    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                   WHERE START_DATE <= '2022-11-30' AND END_DATE >='2022-11-01')
AND CRCDP.DURATION_TYPE = '30일 이상'
AND ROUND(CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) / 100) * 30 >= 500000 AND ROUND(CRCC.DAILY_FEE * (100 - CRCDP.DISCOUNT_RATE) / 100) * 30<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC
                  