WITH ECOLI_RANK AS
(
    SELECT ID, 
    NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANKING
    FROM ECOLI_DATA
)

SELECT ID,
    CASE
        WHEN RANKING = 1 THEN 'CRITICAL'
        WHEN RANKING = 2 THEN 'HIGH'
        WHEN RANKING = 3 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS COLONY_NAME
FROM ECOLI_RANK
ORDER BY ID