SELECT UGU.USER_ID AS USER_ID, UGU.NICKNAME AS NICKNAME,
    CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4), '-', SUBSTR(UGU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_BOARD AS UGB JOIN USED_GOODS_USER AS UGU ON UGB.WRITER_ID = UGU.USER_ID
GROUP BY UGU.USER_ID
HAVING COUNT(UGB.BOARD_ID) >= 3
ORDER BY USER_ID DESC