SELECT YEAR(ONLINE_SALE.SALES_DATE), 
    MONTH(ONLINE_SALE.SALES_DATE), 
    GENDER, 
    COUNT(DISTINCT(USER_INFO.USER_ID))
FROM USER_INFO JOIN ONLINE_SALE 
    ON USER_INFO.USER_ID = ONLINE_SALE.USER_ID
WHERE USER_INFO.GENDER IS NOT NULL
GROUP BY YEAR(ONLINE_SALE.SALES_DATE), 
    MONTH(ONLINE_SALE.SALES_DATE), 
    USER_INFO.GENDER
ORDER BY 1,2,3