WITH CNT AS
(
    SELECT COUNT(*) AS CNT_USER
    FROM USER_INFO
    WHERE YEAR(JOINED)=2021
)
SELECT YEAR(OS.SALES_DATE) AS YEAR,
        MONTH(OS.SALES_DATE) AS MONTH, 
        COUNT(DISTINCT(OS.USER_ID)) AS PURCHASED_USERS, 
        ROUND(COUNT(DISTINCT(OS.USER_ID))/(SELECT CNT_USER FROM CNT),1) AS PURCHASED_RATIO
FROM USER_INFO AS UI JOIN ONLINE_SALE AS OS ON UI.USER_ID = OS.USER_ID
WHERE YEAR(UI.JOINED)=2021 AND YEAR(OS.SALES_DATE)=2022
GROUP BY MONTH(OS.SALES_DATE)