SELECT DISTINCT(CAR_ID), IF(CAR_ID IN (SELECT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS A
WHERE A.START_DATE <= '2022-10-16' AND A.END_DATE >='2022-10-16'
GROUP BY A.CAR_ID), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
ORDER BY CAR_ID DESC
