WITH TRUCK AS (
    SELECT 
        CRCC.DAILY_FEE AS DAILY_FEE, 
        CRCC.CAR_TYPE,
        CRCRH.HISTORY_ID AS HISTORY_ID, 
        DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1 AS DATEDIFF,
        CASE
            WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 90 THEN '90일 이상'
            WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 30 THEN '30일 이상'
            WHEN (DATEDIFF(CRCRH.END_DATE, CRCRH.START_DATE) + 1) >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM 
        CAR_RENTAL_COMPANY_CAR AS CRCC 
    JOIN 
        CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH 
        ON CRCC.CAR_ID = CRCRH.CAR_ID
    WHERE 
        CRCC.CAR_TYPE = '트럭'
)

SELECT 
    T.HISTORY_ID AS HISTORY_ID, 
    ROUND(T.DAILY_FEE * (1 - IFNULL(CRCDP.DISCOUNT_RATE, 0) / 100) * T.DATEDIFF) AS FEE
FROM 
    TRUCK AS T
LEFT JOIN 
    CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS CRCDP 
    ON T.DURATION_TYPE = CRCDP.DURATION_TYPE AND T.CAR_TYPE = CRCDP.CAR_TYPE
ORDER BY 
    FEE DESC, HISTORY_ID DESC;
