SELECT FH.FLAVOR
FROM FIRST_HALF AS FH RIGHT JOIN JULY AS J ON FH.FLAVOR = J.FLAVOR
GROUP BY FH.FLAVOR
ORDER BY FH.TOTAL_ORDER+SUM(J.TOTAL_ORDER) DESC
LIMIT 3

# SELECT *
# FROM FIRST_HALF

# SELECT *
# FROM JULY