# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM FIRST_HALF
# GROUP BY FLAVOR

# SELECT FLAVOR, SUM(TOTAL_ORDER)
# FROM JULY
# GROUP BY FLAVOR

# SELECT FIRST_HALF.FLAVOR, SUM(FIRST_HALF.TOTAL_ORDER)
SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF JOIN JULY ON FIRST_HALF.FLAVOR = JULY.FLAVOR
GROUP BY FIRST_HALF.FLAVOR
ORDER BY FIRST_HALF.TOTAL_ORDER+SUM(JULY.TOTAL_ORDER) DESC
LIMIT 3
# HAVING DISTINCT(FIRST_HALF.SHIPMENT_ID)