WITH MAXS AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT MAXS.YEAR AS YEAR, 
    MAXS.SIZE_OF_COLONY - ECOLI_DATA.SIZE_OF_COLONY AS YEAR_DEV, 
    ECOLI_DATA.ID AS ID
FROM ECOLI_DATA JOIN MAXS ON YEAR(ECOLI_DATA.DIFFERENTIATION_DATE) = MAXS.YEAR
ORDER BY 1, 2
