WITH MAX_ID AS
(
    SELECT MAX(SIZE_OF_COLONY) AS MAX_SIZE, YEAR(DIFFERENTIATION_DATE) AS YEAR
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
        MAX_SIZE - SIZE_OF_COLONY AS YEAR_DEV, 
        ID
FROM ECOLI_DATA AS ED JOIN MAX_ID AS MI ON YEAR(ED.DIFFERENTIATION_DATE) = MI.YEAR
ORDER BY YEAR, YEAR_DEV