SELECT DISTINCT(CRCRH.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR AS CRCC JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS CRCRH ON CRCC.CAR_ID = CRCRH.CAR_ID
WHERE CRCC.CAR_TYPE = '세단' AND DATE_FORMAT(CRCRH.START_DATE,'%m')='10'
ORDER BY CRCC.CAR_ID DESC