WITH MAXS AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FISH_INFO.ID AS ID, FISH_NAME_INFO.FISH_NAME AS FISH_NAME, MAXS.LENGTH AS LENGTH
FROM MAXS JOIN FISH_INFO 
    ON MAXS.FISH_TYPE = FISH_INFO.FISH_TYPE AND MAXS.LENGTH = FISH_INFO.LENGTH
    JOIN FISH_NAME_INFO ON MAXS.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY ID



