WITH MAXS AS (
    SELECT FISH_TYPE, MAX(LENGTH) AS LENGTH
    FROM FISH_INFO
    GROUP BY FISH_TYPE
)

SELECT FISH_INFO.ID AS ID, FISH_NAME_INFO.FISH_NAME AS FISH_NAME, MAXS.LENGTH AS LENGTH
FROM MAXS JOIN FISH_INFO 
    ON MAXS.FISH_TYPE = FISH_INFO.FISH_TYPE AND MAXS.LENGTH = FISH_INFO.LENGTH
    JOIN FISH_NAME_INFO ON MAXS.FISH_TYPE = FISH_NAME_INFO.FISH_TYPE
ORDER BY ID

# WITH RESULT AS(
# SELECT ID,FISH_TYPE, LENGTH, RANK() OVER(PARTITION BY FISH_TYPE ORDER BY LENGTH DESC) AS "RANK"
# FROM FISH_INFO
# )

# SELECT R.ID, B.FISH_NAME, R.LENGTH
# FROM RESULT R JOIN FISH_NAME_INFO B ON R.FISH_TYPE = B.FISH_TYPE
# wHERE R.RANK = 1
# ORDER BY 1