SELECT SUM(HG.SCORE) AS SCORE, 
        HG.EMP_NO, 
        HE.EMP_NAME, 
        HE.POSITION, 
        HE.EMAIL
FROM HR_GRADE AS HG JOIN HR_EMPLOYEES AS HE 
        ON HG.EMP_NO = HE.EMP_NO
WHERE HG.YEAR = 2022
GROUP BY HG.EMP_NO
ORDER BY SCORE DESC
LIMIT 1