WITH MAXS AS (
    SELECT CATEGORY, MAX(PRICE) AS PRICE
        FROM FOOD_PRODUCT
        WHERE CATEGORY IN ('과자', '국', '김치', '식용유')
        GROUP BY CATEGORY )
        
SELECT FOOD_PRODUCT.CATEGORY, FOOD_PRODUCT.PRICE, FOOD_PRODUCT.PRODUCT_NAME
FROM FOOD_PRODUCT JOIN MAXS ON FOOD_PRODUCT.CATEGORY = MAXS.CATEGORY
    AND FOOD_PRODUCT.PRICE = MAXS.PRICE
ORDER BY 2 DESC